SUPPORTED:

dataset_dir: W:\Datasets\AIHUB\korean_image

x_ext: jpg
y_ext: json

checklist:
    all: null
    train1/source: 
        all: false
        간판:
            all: null
            가로형간판: false
            돌출간판: false
            세로형간판: false
            실내간판: false
            실내안내판: false
            지주이용간판: false
            창문이용광고물: false
            현수막: false
        책표지: 
            all: true
            기타: false
            종교: false
            총류: false
    val1/source: 
        all: false
        간판:
            all: null
            가로형간판: false
            돌출간판: false
            세로형간판: false
            실내간판: false
            실내안내판: false
            지주이용간판: false
            창문이용광고물: false
            현수막: false
        책표지: 
            all: true
            기타: false
            종교: false
            총류: false
    train2/source: 
        all: false
        간판:
            all: null
            가로형간판/가로형간판1: false
            가로형간판/가로형간판2: false
            가로형간판/가로형간판3: false
            가로형간판/가로형간판4: false
            가로형간판/가로형간판5: false
            돌출간판/돌출간판1: false
            돌출간판/돌출간판2: false
            세로형간판: false
            실내간판/실내간판1: false
            실내간판/실내간판2: false
            실내안내판/실내안내판1: false
            실내안내판/실내안내판2: false
            지주이용간판: false
            창문이용광고물: false
            현수막: false
        책표지: 
            all: true
            총류: false
            철학: false
            종교: false
            사회과학: false
            자연과학: false
            기술과학: false
            예술: false
            언어: false
            문학: false
            역사: false
            기타: false
    val2/source: 
        all: null
        간판:
            all: false
            가로형간판: false
            돌출간판: false
            세로형간판: false
            실내간판: false
            실내안내판: false
            지주이용간판: false
            창문이용광고물: false
            현수막: false
        책표지: 
            all: null
            총류: true
            철학: false
            종교: false
            사회과학: false
            자연과학: false
            기술과학: false
            예술: false
            언어: false
            문학: false
            역사: false
            기타: false

file_path_rename_pair:
    030.야외 실제 촬영 한글 이미지/01.데이터/1.Training/라벨링데이터_230216_add/TL1/1.간판/가로형간판: train1/label/간판/가로형간판
    030.야외 실제 촬영 한글 이미지/01.데이터/1.Training/라벨링데이터_230216_add/TL1/1.간판/돌출간판: train1/label/간판/돌출간판
    030.야외 실제 촬영 한글 이미지/01.데이터/1.Training/라벨링데이터_230216_add/TL1/1.간판/세로형간판: train1/label/간판/세로형간판
    030.야외 실제 촬영 한글 이미지/01.데이터/1.Training/라벨링데이터_230216_add/TL1/1.간판/실내간판: train1/label/간판/실내간판
    030.야외 실제 촬영 한글 이미지/01.데이터/1.Training/라벨링데이터_230216_add/TL1/1.간판/실내안내판: train1/label/간판/실내안내판
    030.야외 실제 촬영 한글 이미지/01.데이터/1.Training/라벨링데이터_230216_add/TL1/1.간판/지주이용간판: train1/label/간판/지주이용간판
    030.야외 실제 촬영 한글 이미지/01.데이터/1.Training/라벨링데이터_230216_add/TL1/1.간판/창문이용광고물: train1/label/간판/창문이용광고물
    030.야외 실제 촬영 한글 이미지/01.데이터/1.Training/라벨링데이터_230216_add/TL1/1.간판/현수막: train1/label/간판/현수막
    030.야외 실제 촬영 한글 이미지/01.데이터/1.Training/라벨링데이터_230216_add/TL1/2.책표지/기타: train1/label/책표지/기타
    030.야외 실제 촬영 한글 이미지/01.데이터/1.Training/라벨링데이터_230216_add/TL1/2.책표지/종교: train1/label/책표지/종교
    030.야외 실제 촬영 한글 이미지/01.데이터/1.Training/라벨링데이터_230216_add/TL1/2.책표지/총류: train1/label/책표지/총류
    030.야외 실제 촬영 한글 이미지/01.데이터/1.Training/원천데이터_230216_add/TS1/1.간판/가로형간판: train1/source/간판/가로형간판
    030.야외 실제 촬영 한글 이미지/01.데이터/1.Training/원천데이터_230216_add/TS1/1.간판/돌출간판: train1/source/간판/돌출간판
    030.야외 실제 촬영 한글 이미지/01.데이터/1.Training/원천데이터_230216_add/TS1/1.간판/세로형간판: train1/source/간판/세로형간판
    030.야외 실제 촬영 한글 이미지/01.데이터/1.Training/원천데이터_230216_add/TS1/1.간판/실내간판: train1/source/간판/실내간판
    030.야외 실제 촬영 한글 이미지/01.데이터/1.Training/원천데이터_230216_add/TS1/1.간판/실내안내판: train1/source/간판/실내안내판
    030.야외 실제 촬영 한글 이미지/01.데이터/1.Training/원천데이터_230216_add/TS1/1.간판/지주이용간판: train1/source/간판/지주이용간판
    030.야외 실제 촬영 한글 이미지/01.데이터/1.Training/원천데이터_230216_add/TS1/1.간판/창문이용광고물: train1/source/간판/창문이용광고물
    030.야외 실제 촬영 한글 이미지/01.데이터/1.Training/원천데이터_230216_add/TS1/1.간판/현수막: train1/source/간판/현수막
    030.야외 실제 촬영 한글 이미지/01.데이터/1.Training/원천데이터_230216_add/TS1/2.책표지/기타: train1/source/책표지/기타
    030.야외 실제 촬영 한글 이미지/01.데이터/1.Training/원천데이터_230216_add/TS1/2.책표지/종교: train1/source/책표지/종교
    030.야외 실제 촬영 한글 이미지/01.데이터/1.Training/원천데이터_230216_add/TS1/2.책표지/총류: train1/source/책표지/총류

    030.야외 실제 촬영 한글 이미지/01.데이터/2.Validation/라벨링데이터_230216_add/VL1/1.간판/가로형간판: val1/label/간판/가로형간판
    030.야외 실제 촬영 한글 이미지/01.데이터/2.Validation/라벨링데이터_230216_add/VL1/1.간판/돌출간판: val1/label/간판/돌출간판
    030.야외 실제 촬영 한글 이미지/01.데이터/2.Validation/라벨링데이터_230216_add/VL1/1.간판/세로형간판: val1/label/간판/세로형간판
    030.야외 실제 촬영 한글 이미지/01.데이터/2.Validation/라벨링데이터_230216_add/VL1/1.간판/실내간판: val1/label/간판/실내간판
    030.야외 실제 촬영 한글 이미지/01.데이터/2.Validation/라벨링데이터_230216_add/VL1/1.간판/실내안내판: val1/label/간판/실내안내판
    030.야외 실제 촬영 한글 이미지/01.데이터/2.Validation/라벨링데이터_230216_add/VL1/1.간판/지주이용간판: val1/label/간판/지주이용간판
    030.야외 실제 촬영 한글 이미지/01.데이터/2.Validation/라벨링데이터_230216_add/VL1/1.간판/창문이용광고물: val1/label/간판/창문이용광고물
    030.야외 실제 촬영 한글 이미지/01.데이터/2.Validation/라벨링데이터_230216_add/VL1/1.간판/현수막: val1/label/간판/현수막
    030.야외 실제 촬영 한글 이미지/01.데이터/2.Validation/라벨링데이터_230216_add/VL1/2.책표지/기타: val1/label/책표지/기타
    030.야외 실제 촬영 한글 이미지/01.데이터/2.Validation/라벨링데이터_230216_add/VL1/2.책표지/종교: val1/label/책표지/종교
    030.야외 실제 촬영 한글 이미지/01.데이터/2.Validation/라벨링데이터_230216_add/VL1/2.책표지/총류: val1/label/책표지/총류
    030.야외 실제 촬영 한글 이미지/01.데이터/2.Validation/원천데이터_230216_add/VS1/1.간판/가로형간판: val1/source/간판/가로형간판
    030.야외 실제 촬영 한글 이미지/01.데이터/2.Validation/원천데이터_230216_add/VS1/1.간판/돌출간판: val1/source/간판/돌출간판
    030.야외 실제 촬영 한글 이미지/01.데이터/2.Validation/원천데이터_230216_add/VS1/1.간판/세로형간판: val1/source/간판/세로형간판
    030.야외 실제 촬영 한글 이미지/01.데이터/2.Validation/원천데이터_230216_add/VS1/1.간판/실내간판: val1/source/간판/실내간판
    030.야외 실제 촬영 한글 이미지/01.데이터/2.Validation/원천데이터_230216_add/VS1/1.간판/실내안내판: val1/source/간판/실내안내판
    030.야외 실제 촬영 한글 이미지/01.데이터/2.Validation/원천데이터_230216_add/VS1/1.간판/지주이용간판: val1/source/간판/지주이용간판
    030.야외 실제 촬영 한글 이미지/01.데이터/2.Validation/원천데이터_230216_add/VS1/1.간판/창문이용광고물: val1/source/간판/창문이용광고물
    030.야외 실제 촬영 한글 이미지/01.데이터/2.Validation/원천데이터_230216_add/VS1/1.간판/현수막: val1/source/간판/현수막
    030.야외 실제 촬영 한글 이미지/01.데이터/2.Validation/원천데이터_230216_add/VS1/2.책표지/기타: val1/source/책표지/기타
    030.야외 실제 촬영 한글 이미지/01.데이터/2.Validation/원천데이터_230216_add/VS1/2.책표지/종교: val1/source/책표지/종교
    030.야외 실제 촬영 한글 이미지/01.데이터/2.Validation/원천데이터_230216_add/VS1/2.책표지/총류: val1/source/책표지/총류
            
    야외 실제 촬영 한글 이미지/Training/[라벨]Training/1.간판/1.가로형간판/가로형간판1: train2/label/간판/가로형간판/가로형간판1
    야외 실제 촬영 한글 이미지/Training/[라벨]Training/1.간판/1.가로형간판/가로형간판2: train2/label/간판/가로형간판/가로형간판2
    야외 실제 촬영 한글 이미지/Training/[라벨]Training/1.간판/1.가로형간판/가로형간판3: train2/label/간판/가로형간판/가로형간판3
    야외 실제 촬영 한글 이미지/Training/[라벨]Training/1.간판/1.가로형간판/가로형간판4: train2/label/간판/가로형간판/가로형간판4
    야외 실제 촬영 한글 이미지/Training/[라벨]Training/1.간판/1.가로형간판/가로형간판5: train2/label/간판/가로형간판/가로형간판5
    야외 실제 촬영 한글 이미지/Training/[라벨]Training/1.간판/2.돌출간판/돌출간판1:     train2/label/간판/돌출간판/돌출간판1
    야외 실제 촬영 한글 이미지/Training/[라벨]Training/1.간판/2.돌출간판/돌출간판2:     train2/label/간판/돌출간판/돌출간판2
    야외 실제 촬영 한글 이미지/Training/[라벨]Training/1.간판/3.세로형간판":            train2/label/간판/세로형간판
    야외 실제 촬영 한글 이미지/Training/[라벨]Training/1.간판/4.실내간판/실내간판1:     train2/label/간판/실내간판/실내간판1
    야외 실제 촬영 한글 이미지/Training/[라벨]Training/1.간판/4.실내간판/실내간판2:     train2/label/간판/실내간판/실내간판2
    야외 실제 촬영 한글 이미지/Training/[라벨]Training/1.간판/5.실내안내판/새 폴더:     train2/label/간판/실내안내판/실내안내판1
    야외 실제 촬영 한글 이미지/Training/[라벨]Training/1.간판/5.실내안내판/새 폴더 (2): train2/label/간판/실내안내판/실내안내판2
    야외 실제 촬영 한글 이미지/Training/[라벨]Training/1.간판/6.지주이용간판:           train2/label/간판/지주이용간판
    야외 실제 촬영 한글 이미지/Training/[라벨]Training/1.간판/7.창문이용광고물:         train2/label/간판/창문이용광고물
    야외 실제 촬영 한글 이미지/Training/[라벨]Training/1.간판/8.현수막:                 train2/label/간판/현수막
    야외 실제 촬영 한글 이미지/Training/[라벨]Training/2.책표지/01.총류:                train2/label/책표지/총류
    야외 실제 촬영 한글 이미지/Training/[라벨]Training/2.책표지/02.철학:                train2/label/책표지/철학
    야외 실제 촬영 한글 이미지/Training/[라벨]Training/2.책표지/03.종교:                train2/label/책표지/종교
    야외 실제 촬영 한글 이미지/Training/[라벨]Training/2.책표지/04.사회과학:            train2/label/책표지/사회과학
    야외 실제 촬영 한글 이미지/Training/[라벨]Training/2.책표지/05.자연과학:            train2/label/책표지/자연과학
    야외 실제 촬영 한글 이미지/Training/[라벨]Training/2.책표지/06.기술과학:            train2/label/책표지/기술과학
    야외 실제 촬영 한글 이미지/Training/[라벨]Training/2.책표지/07.예술:                train2/label/책표지/예술
    야외 실제 촬영 한글 이미지/Training/[라벨]Training/2.책표지/08.언어:                train2/label/책표지/언어
    야외 실제 촬영 한글 이미지/Training/[라벨]Training/2.책표지/09.문학:                train2/label/책표지/문학
    야외 실제 촬영 한글 이미지/Training/[라벨]Training/2.책표지/10.역사:                train2/label/책표지/역사
    야외 실제 촬영 한글 이미지/Training/[라벨]Training/2.책표지/11.기타:                train2/label/책표지/기타
        
    야외 실제 촬영 한글 이미지/Training/[원천]Training_간판_가로형간판_원천데이터1: train2/source/간판/가로형간판/가로형간판1
    야외 실제 촬영 한글 이미지/Training/[원천]Training_간판_가로형간판_원천데이터2: train2/source/간판/가로형간판/가로형간판2
    야외 실제 촬영 한글 이미지/Training/[원천]Training_간판_가로형간판_원천데이터3: train2/source/간판/가로형간판/가로형간판3
    야외 실제 촬영 한글 이미지/Training/[원천]Training_간판_가로형간판_원천데이터4: train2/source/간판/가로형간판/가로형간판4
    야외 실제 촬영 한글 이미지/Training/[원천]Training_간판_가로형간판_원천데이터5: train2/source/간판/가로형간판/가로형간판5
    야외 실제 촬영 한글 이미지/Training/[원천]Training_간판_돌출간판_원천데이터1: train2/source/간판/돌출간판/돌출간판1
    야외 실제 촬영 한글 이미지/Training/[원천]Training_간판_돌출간판_원천데이터2: train2/source/간판/돌출간판/돌출간판2
    야외 실제 촬영 한글 이미지/Training/[원천]Training_간판_세로형간판_원천데이터: train2/source/간판/세로형간판
    야외 실제 촬영 한글 이미지/Training/[원천]Training_간판_실내간판_원천데이터1: train2/source/간판/실내간판/실내간판1
    야외 실제 촬영 한글 이미지/Training/[원천]Training_간판_실내간판_원천데이터2: train2/source/간판/실내간판/실내간판2
    야외 실제 촬영 한글 이미지/Training/[원천]Training_간판_실내안내판_원천데이터1: train2/source/간판/실내안내판/실내안내판1
    야외 실제 촬영 한글 이미지/Training/[원천]Training_간판_실내안내판_원천데이터2: train2/source/간판/실내안내판/실내안내판2
    야외 실제 촬영 한글 이미지/Training/[원천]Training_간판_지주이용간판_원천데이터: train2/source/간판/지주이용간판
    야외 실제 촬영 한글 이미지/Training/[원천]Training_간판_창문이용광고물_원천데이터: train2/source/간판/창문이용광고물
    야외 실제 촬영 한글 이미지/Training/[원천]Training_간판_현수막_원천데이터: train2/source/간판/현수막
        
    야외 실제 촬영 한글 이미지/Training/[원천]Training_책표지1/01.총류: train2/source/책표지/총류
    야외 실제 촬영 한글 이미지/Training/[원천]Training_책표지1/02.철학: train2/source/책표지/철학
    야외 실제 촬영 한글 이미지/Training/[원천]Training_책표지1/03.종교: train2/source/책표지/종교
    야외 실제 촬영 한글 이미지/Training/[원천]Training_책표지1/04.사회과학: train2/source/책표지/사회과학
    야외 실제 촬영 한글 이미지/Training/[원천]Training_책표지2/05.자연과학: train2/source/책표지/자연과학
    야외 실제 촬영 한글 이미지/Training/[원천]Training_책표지2/06.기술과학: train2/source/책표지/기술과학
    야외 실제 촬영 한글 이미지/Training/[원천]Training_책표지2/07.예술: train2/source/책표지/예술
    야외 실제 촬영 한글 이미지/Training/[원천]Training_책표지2/08.언어: train2/source/책표지/언어
    야외 실제 촬영 한글 이미지/Training/[원천]Training_책표지3/09.문학: train2/source/책표지/문학
    야외 실제 촬영 한글 이미지/Training/[원천]Training_책표지3/10.역사: train2/source/책표지/역사
    야외 실제 촬영 한글 이미지/Training/[원천]Training_책표지3/11.기타: train2/source/책표지/기타

    야외 실제 촬영 한글 이미지/Validation/[라벨]Validation/1.간판/1.가로형간판: val2/label/간판/가로형간판
    야외 실제 촬영 한글 이미지/Validation/[라벨]Validation/1.간판/2.돌출간판: val2/label/간판/돌출간판
    야외 실제 촬영 한글 이미지/Validation/[라벨]Validation/1.간판/3.세로형간판: val2/label/간판/세로형간판
    야외 실제 촬영 한글 이미지/Validation/[라벨]Validation/1.간판/4.실내간판: val2/label/간판/실내간판
    야외 실제 촬영 한글 이미지/Validation/[라벨]Validation/1.간판/5.실내안내판: val2/label/간판/실내안내판
    야외 실제 촬영 한글 이미지/Validation/[라벨]Validation/1.간판/6.지주이용간판: val2/label/간판/지주이용간판
    야외 실제 촬영 한글 이미지/Validation/[라벨]Validation/1.간판/7.창문이용광고물: val2/label/간판/창문이용광고물
    야외 실제 촬영 한글 이미지/Validation/[라벨]Validation/1.간판/8.현수막: val2/label/간판/현수막
    야외 실제 촬영 한글 이미지/Validation/[라벨]Validation/2.책표지/01.총류: val2/label/책표지/총류
    야외 실제 촬영 한글 이미지/Validation/[라벨]Validation/2.책표지/02.철학: val2/label/책표지/철학
    야외 실제 촬영 한글 이미지/Validation/[라벨]Validation/2.책표지/03.종교: val2/label/책표지/종교
    야외 실제 촬영 한글 이미지/Validation/[라벨]Validation/2.책표지/04.사회과학: val2/label/책표지/사회과학
    야외 실제 촬영 한글 이미지/Validation/[라벨]Validation/2.책표지/05.자연과학: val2/label/책표지/자연과학
    야외 실제 촬영 한글 이미지/Validation/[라벨]Validation/2.책표지/06.기술과학: val2/label/책표지/기술과학
    야외 실제 촬영 한글 이미지/Validation/[라벨]Validation/2.책표지/07.예술: val2/label/책표지/예술
    야외 실제 촬영 한글 이미지/Validation/[라벨]Validation/2.책표지/08.언어: val2/label/책표지/언어
    야외 실제 촬영 한글 이미지/Validation/[라벨]Validation/2.책표지/09.문학: val2/label/책표지/문학
    야외 실제 촬영 한글 이미지/Validation/[라벨]Validation/2.책표지/10.역사: val2/label/책표지/역사
    야외 실제 촬영 한글 이미지/Validation/[라벨]Validation/2.책표지/11.기타: val2/label/책표지/기타
        
    야외 실제 촬영 한글 이미지/Validation/01.가로형간판: val2/source/간판/가로형간판
    야외 실제 촬영 한글 이미지/Validation/[원천]Validation_간판2/02.돌출간판: val2/source/간판/돌출간판
    야외 실제 촬영 한글 이미지/Validation/[원천]Validation_간판2/03.세로형간판: val2/source/간판/세로형간판
    야외 실제 촬영 한글 이미지/Validation/[원천]Validation_간판2/04.실내간판: val2/source/간판/실내간판
    야외 실제 촬영 한글 이미지/Validation/[원천]Validation_간판2/05.실내안내판: val2/source/간판/실내안내판
    야외 실제 촬영 한글 이미지/Validation/[원천]Validation_간판3/06.지주이용간판: val2/source/간판/지주이용간판
    야외 실제 촬영 한글 이미지/Validation/[원천]Validation_간판3/07.창문이용광고물: val2/source/간판/창문이용광고물
    야외 실제 촬영 한글 이미지/Validation/[원천]Validation_간판3/08.현수막: val2/source/간판/현수막
        
    야외 실제 촬영 한글 이미지/Validation/[원천]Validation_책표지/01.총류: val2/source/책표지/총류
    야외 실제 촬영 한글 이미지/Validation/[원천]Validation_책표지/02.철학: val2/source/책표지/철학
    야외 실제 촬영 한글 이미지/Validation/[원천]Validation_책표지/03.종교: val2/source/책표지/종교
    야외 실제 촬영 한글 이미지/Validation/[원천]Validation_책표지/04.사회과학: val2/source/책표지/사회과학
    야외 실제 촬영 한글 이미지/Validation/[원천]Validation_책표지/05.자연과학: val2/source/책표지/자연과학
    야외 실제 촬영 한글 이미지/Validation/[원천]Validation_책표지/06.기술과학: val2/source/책표지/기술과학
    야외 실제 촬영 한글 이미지/Validation/[원천]Validation_책표지/07.예술: val2/source/책표지/예술
    야외 실제 촬영 한글 이미지/Validation/[원천]Validation_책표지/08.언어: val2/source/책표지/언어
    야외 실제 촬영 한글 이미지/Validation/[원천]Validation_책표지/09.문학: val2/source/책표지/문학
    야외 실제 촬영 한글 이미지/Validation/[원천]Validation_책표지/10.역사: val2/source/책표지/역사
    야외 실제 촬영 한글 이미지/Validation/[원천]Validation_책표지/11.기타: val2/source/책표지/기타
        